name: relu
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - appnope=0.1.3
  - asttokens=2.2.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.0.7
  - convertdate=2.4.0
  - cryptography=39.0.1
  - cycler=0.11.0
  - dacite=1.8.0
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - executing=1.2.0
  - ffmpeg=4.3
  - filelock=3.9.0
  - fonttools=4.39.4
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - hijri-converter=2.3.1
  - holidays=0.25
  - htmlmin=0.1.12
  - icu=58.2
  - idna=3.4
  - imagehash=4.3.1
  - importlib-metadata=6.6.0
  - importlib-resources=5.12.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - intel-openmp=2023.1.0
  - ipykernel=6.23.1
  - ipython=8.4.0
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.2.0
  - jupyter_core=4.12.0
  - kiwisolver=1.4.4
  - korean_lunar_calendar=0.3.1
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxgboost=1.7.4
  - libxml2=2.10.3
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - multimethod=1.4
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.8.4
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openpyxl=3.0.9
  - openssl=1.1.1u
  - packaging=23.1
  - pandas=1.4.2
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - phik=0.12.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=3.5.1
  - pooch=1.7.0
  - prompt-toolkit=3.0.38
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.7.4
  - pybind11-abi=4
  - pycparser=2.21
  - pydantic=1.10.8
  - pygments=2.15.1
  - pymeeus=0.5.12
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.0.1
  - pytz=2022.1
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.0.2
  - readline=8.2
  - requests=2.29.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - sympy=1.11.1
  - tangled-up-in-unicode=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typeguard=2.13.3
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - visions=0.7.5
  - wcwidth=0.2.6
  - wheel=0.38.4
  - wordcloud=1.9.2
  - xgboost=1.7.4
  - xz=5.4.2
  - yaml=0.2.5
  - ydata-profiling=4.2.0
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - aiostream==0.4.5
    - altair==5.0.1
    - anyio==3.7.0
    - asgiref==3.7.2
    - async-timeout==4.0.2
    - build==0.10.0
    - click==8.1.3
    - cloudpickle==2.0.0
    - exceptiongroup==1.1.1
    - fastapi==0.97.0
    - fastjsonschema==2.17.1
    - ffmpy==0.3.0
    - frozenlist==1.3.3
    - fsspec==2023.6.0
    - gradio==3.35.2
    - gradio-client==0.2.7
    - grpclib==0.4.3
    - h11==0.14.0
    - h2==4.1.0
    - hpack==4.0.0
    - httpcore==0.17.2
    - httpx==0.24.1
    - huggingface-hub==0.15.1
    - hyperframe==6.0.1
    - jsonschema==4.17.3
    - linkify-it-py==2.0.2
    - markdown-it-py==2.2.0
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - modal-client==0.49.2437
    - multidict==6.0.4
    - nbformat==5.9.1
    - orjson==3.9.1
    - pip-tools==6.14.0
    - pkgutil-resolve-name==1.3.10
    - plotly==5.15.0
    - protobuf==4.23.3
    - pydub==0.25.1
    - pyproject-hooks==1.0.0
    - pyrsistent==0.19.3
    - python-multipart==0.0.6
    - rich==13.4.2
    - semantic-version==2.10.0
    - sigtools==4.0.1
    - sniffio==1.3.0
    - starlette==0.27.0
    - synchronicity==0.5.3
    - tblib==1.7.0
    - tenacity==8.2.2
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - typer==0.9.0
    - types-certifi==2021.10.8.3
    - types-toml==0.10.8.6
    - uc-micro-py==1.0.2
    - uvicorn==0.22.0
    - watchfiles==0.19.0
    - websockets==11.0.3
    - yarl==1.9.2

