wandb_version: 1

colsample_bytree:
  desc: null
  value: 0.8735137482594453
learning_rate:
  desc: null
  value: 0.027185695322436303
max_depth:
  desc: null
  value: 4
n_estimators:
  desc: null
  value: 163
reg_alpha:
  desc: null
  value: 0.8810997547541417
reg_lambda:
  desc: null
  value: 0.7836773632494645
subsample:
  desc: null
  value: 0.893641961678205
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690392703.015456
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.16
      5: 0.15.5
      8:
      - 1
      - 5
