wandb_version: 1

colsample_bytree:
  desc: null
  value: 0.6552459925130901
learning_rate:
  desc: null
  value: 0.0819174086142608
max_depth:
  desc: null
  value: 9
n_estimators:
  desc: null
  value: 83
reg_alpha:
  desc: null
  value: 0.8594462174758332
reg_lambda:
  desc: null
  value: 0.8676746911040444
subsample:
  desc: null
  value: 0.7695011764118034
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690396691.45554
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.8.16
      5: 0.15.5
      8:
      - 1
      - 5
