wandb_version: 1

colsample_bytree:
  desc: null
  value: 0.8735137482594453
learning_rate:
  desc: null
  value: 0.027185695322436303
max_depth:
  desc: null
  value: 4
n_estimators:
  desc: null
  value: 163
reg_alpha:
  desc: null
  value: 0.8810997547541417
reg_lambda:
  desc: null
  value: 0.7836773632494645
subsample:
  desc: null
  value: 0.893641961678205
_items:
  desc: null
  value:
    colsample_bytree: 0.8735137482594453
    learning_rate: 0.027185695322436303
    max_depth: 4
    n_estimators: 163
    reg_alpha: 0.8810997547541417
    reg_lambda: 0.7836773632494645
    subsample: 0.893641961678205
    _wandb: {}
_locked:
  desc: null
  value:
    colsample_bytree: 0
    learning_rate: 0
    max_depth: 0
    n_estimators: 0
    reg_alpha: 0
    reg_lambda: 0
    subsample: 0
_users:
  desc: null
  value:
    sweep: 0
_users_inv:
  desc: null
  value:
    '0': sweep
_users_cnt:
  desc: null
  value: 1
_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_callback
_settings:
  desc: null
  value: '<Settings {''_args'': None, ''_aws_lambda'': False, ''_async_upload_concurrency_limit'':
    None, ''_cli_only_mode'': None, ''_colab'': False, ''_config_dict'': None, ''_console'':
    <SettingsConsole.WRAP: 1>, ''_cuda'': None, ''_disable_meta'': None, ''_disable_service'':
    False, ''_disable_stats'': None, ''_disable_viewer'': None, ''_disable_setproctitle'':
    False, ''_except_exit'': None, ''_executable'': ''/Users/servandodavidtorresgarcia/miniconda3/envs/relu/bin/python'',
    ''_extra_http_headers'': None, ''_flow_control_custom'': False, ''_flow_control_disabled'':
    False, ''_internal_check_process'': 8, ''_internal_queue_timeout'': 2, ''_ipython'':
    False, ''_jupyter'': True, ''_jupyter_name'': None, ''_jupyter_path'': None, ''_jupyter_root'':
    None, ''_kaggle'': False, ''_live_policy_rate_limit'': None, ''_live_policy_wait_time'':
    None, ''_log_level'': None, ''_network_buffer'': None, ''_noop'': False, ''_notebook'':
    True, ''_offline'': False, ''_sync'': False, ''_os'': ''macOS-10.16-x86_64-i386-64bit'',
    ''_platform'': ''darwin'', ''_python'': ''3.8.16'', ''_runqueue_item_id'': None,
    ''_require_nexus'': False, ''_save_requirements'': True, ''_service_transport'':
    None, ''_service_wait'': 30.0, ''_start_datetime'': datetime.datetime(2023, 7,
    26, 20, 31, 42, 989300), ''_start_time'': 1690392702.9893, ''_stats_pid'': 2884,
    ''_stats_sample_rate_seconds'': 2.0, ''_stats_samples_to_average'': 15, ''_stats_join_assets'':
    True, ''_stats_neuron_monitor_config_path'': None, ''_stats_open_metrics_endpoints'':
    None, ''_stats_open_metrics_filters'': (''.*'',), ''_tmp_code_dir'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5/tmp/code'',
    ''_tracelog'': None, ''_unsaved_keys'': None, ''_windows'': False, ''allow_val_change'':
    None, ''anonymous'': None, ''api_key'': ''***REDACTED***'', ''azure_account_url_to_access_key'':
    {}, ''base_url'': ''https://api.wandb.ai'', ''code_dir'': None, ''config_paths'':
    None, ''console'': ''auto'', ''deployment'': ''cloud'', ''disable_code'': None,
    ''disable_git'': False, ''disable_hints'': None, ''disable_job_creation'': False,
    ''disabled'': False, ''docker'': None, ''email'': ''vandotorresg@gmail.com'',
    ''entity'': ''servando'', ''files_dir'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5/files'',
    ''force'': None, ''git_commit'': ''2571229c0fde2cb28205ba3bcefcdc2c632571eb'',
    ''git_remote'': ''origin'', ''git_remote_url'': ''https://github.com/Servando1990/Relu.git'',
    ''git_root'': None, ''heartbeat_seconds'': 30, ''host'': ''MacBook-Pro-de-Servando.local'',
    ''ignore_globs'': (), ''init_timeout'': 60.0, ''is_local'': False, ''job_source'':
    None, ''label_disable'': None, ''launch'': None, ''launch_config_path'': None,
    ''log_dir'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5/logs'',
    ''log_internal'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5/logs/debug-internal.log'',
    ''log_symlink_internal'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/debug-internal.log'',
    ''log_symlink_user'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/debug.log'',
    ''log_user'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5/logs/debug.log'',
    ''login_timeout'': None, ''magic'': None, ''mode'': ''online'', ''notebook_name'':
    None, ''problem'': ''fatal'', ''program'': ''<python with no main file>'', ''program_relpath'':
    None, ''project'': ''relu-project'', ''project_url'': ''https://wandb.ai/servando/relu-project'',
    ''quiet'': None, ''reinit'': None, ''relogin'': None, ''resume'': None, ''resume_fname'':
    ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/wandb-resume.json'',
    ''resumed'': False, ''root_dir'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks'',
    ''run_group'': None, ''run_id'': ''qhyiytq5'', ''run_job_type'': None, ''run_mode'':
    ''run'', ''run_name'': ''summer-sweep-1'', ''run_notes'': None, ''run_tags'':
    None, ''run_url'': ''https://wandb.ai/servando/relu-project/runs/qhyiytq5'', ''sagemaker_disable'':
    None, ''save_code'': None, ''settings_system'': ''/Users/servandodavidtorresgarcia/.config/wandb/settings'',
    ''settings_workspace'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/settings'',
    ''show_colors'': None, ''show_emoji'': None, ''show_errors'': True, ''show_info'':
    True, ''show_warnings'': True, ''silent'': False, ''start_method'': None, ''strict'':
    None, ''summary_errors'': None, ''summary_timeout'': 60, ''summary_warnings'':
    5, ''sweep_id'': ''esur1eoq'', ''sweep_param_path'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/sweep-esur1eoq/config-qhyiytq5.yaml'',
    ''sweep_url'': ''https://wandb.ai/servando/relu-project/sweeps/esur1eoq'', ''symlink'':
    True, ''sync_dir'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5'',
    ''sync_file'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5/run-qhyiytq5.wandb'',
    ''sync_symlink_latest'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/latest-run'',
    ''system_sample'': 15, ''system_sample_seconds'': 2, ''table_raise_on_max_row_limit_exceeded'':
    False, ''timespec'': ''20230726_203142'', ''tmp_dir'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/run-20230726_203142-qhyiytq5/tmp'',
    ''username'': ''servandodavidtorresgarcia'', ''wandb_dir'': ''/Users/servandodavidtorresgarcia/Servando/Relu/Relu/notebooks/wandb/''}>'
_artifact_callback:
  desc: null
  value: wandb.sdk.wandb_run.Run._config_artifact_callback
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1690392721.515292
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.16
      5: 0.15.5
      8:
      - 1
      - 5
